name: ROS CI
# https://github.com/orgs/community/discussions/52616#discussioncomment-9364532

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker_image }}
    steps:
      - uses: actions/checkout@v6
        with:
          path: src

      - name: Run sudo apt update
        run: sudo apt -q update

      - name: Run rosdep update
        run: rosdep update

      - name: Install binary dependencies
        run: rosdep install --from-paths src --ignore-src -y -q

      - name: Build packages
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to crx_kinematics crx_kinematics_py

      - name: Run tests
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          colcon test --event-handlers console_cohesion+ --packages-select crx_kinematics crx_kinematics_py

      - name: Check test results
        run: colcon test-result --all --verbose
